---
version: 2.0
steps:
  PRE_BUILD:
  - checkout:
      name: "checkout"
      inputs:
        scm: "codehub"
        url: "git@codehub.devcloud.ap-southeast-3.huaweicloud.com:hfa00002/hfa-vpc-provisioning-environment.git"
        branch: "main"
        lfs: false
        submodule: false
  BUILD:
  - download_artifact:
      inputs:
        url: https://devrepo.devcloud.ap-southeast-3.huaweicloud.com/DevRepoServer/v1/files/download?filename=${codearts_project_id}/terraform/terraform.tfstate
  - sh:
      name: "Install Terraform"
      inputs:
        command: |
          export HW_ACCESS_KEY=${AccessKey}
          export HW_SECRET_KEY=${SecretKey}
          export HW_REGION_NAME=${Region}
          export TF_LOG=DEBUG
          curl -fsSL ${terraform_download_url} -o terraform.zip
          unzip terraform.zip
          cat terraform.tfstate
          ./terraform init
          ./terraform apply -auto-approve -no-color -var="accesskey_agent=${AccessKey}" -var="encrypted_secretkey_agent=${AgentSecretKey}" -var="codearts_cluster_id=${ClusterId}" -var="codearts_project_id=${codearts_project_id}"
  - upload_artifact:
      inputs:
        version: latest
        path: /terraform/terraform.tfstate